# F5 데이터 표현 (배열, 표)
# 넘파이 , 판다스 

# 목차
1. 배열
2. Numpy
3. 데이터의 행렬변환
4. 판다스로 구조화된 데이터보기(series, dataframe)
5. 판다스 기능 사용
6. groupby
7. reshape

# 한줄 정리& 한줄 소감

* Numpy : 행렬이나 다차원 배열을 쉽게 계산하려고 쓰는 파이썬 라이브러리 
* pandas: 넘파이를 기반으로 series와 dataframe(표) 구조를 제공한다.


1. 프로젝트를 진행하면서 넘파이, 판다스 개념이 헷갈리고 정리되지 않은 상태로 머리 속에 있었는데 복습하면서 정리하는 시간이였다.
2. 아직 이해한 단계고 다양하게 적용하기엔 어렵다. 개념을 알아도 내가 가진 데이터에 어떻게 써야할지 더 연습이 필요하다. 

# 1. 배열, 중앙값, 평균, 표준편차

### 배열

array list

### 중앙값
주어진 숫자를 크기순으로 배치했을때 중앙에 위치하는 값


In [ ]:
def median(nums):       
    nums.sort()                 # sort()로 순서대로 정렬
    size = len(nums)
    p = size // 2               # 홀수면 n/2 반올림한 값이 중앙값
    if size % 2 == 0:          # 짝수일때 n/2번째 ((n/2)+1) 
        pr = p   
        pl = p-1               # 반으로 나눠서 기준의 앞값 혹은 뒷값
        mid= float((nums[pl]+nums[pr])/2)    
    else:                               # 리스트의 개수가 홀수일때
        mid = nums[p]
    return mid

print('X :', X)
median(X) 

### 표준편차와 평균

In [3]:
# 평균

def means(nums):
    total = 0.0
    for i in range(len(nums)): #리스트의 길이(5)
        total = total + nums[i] #0번째 숫자 1 +0 - total 1+1번째 숫자 2
    return total / len(nums)

X = [1,2,3,4,5,6]
means(X)

3.5

표준편차 

s(표준편차)=√Σ(x(입력받은 숫자)−¯¯¯x(평균))2/n(입력받은 숫자의개수)−1

* n-1 을 하는 이유 
표본분산은 n-1로 계산해야 모집단의 분산과 같다.
즉, 표분분산을 불편추정량(차이가 없는 추정량 = 서로 같다)을 만들려고 n-1을 함

In [4]:
# 표준편차

avg = means(X)

def std_dev(nums, avg): # 1. 숫자배열과 평균값을 받는다
   texp = 0.0
   for i in range(len(nums)):
       texp = texp + (nums[i] - avg)**2    # 2. 각 입력값과 평균의 차이를 곱하고 제곱한다. 3. 그 총합을 더한다.
   return (texp/(len(nums)-1)) ** 0.5    # 4. 그 총합을 (n-1)로 나누고 제곱근! = 표준편차  

std_dev(X,avg)

1.8708286933869707

### 전체 코드 : main()함수 (클래스에서 더 자세히 설명)
프로그램의 시작점이 어딘지 알려주는 함수 

* 평균값, 중앙값, 표준편차 구하기 
1. 숫자 리스트를 만든다.
2. 평균값, 중앙값을 구한다.
3. 표준편차를 구한다. 
4. 각 함수를 쓰고 main 함수에 해당 함수를 넣어서 실행한다.

# 2. Numpy

 Numpy : 행렬이나 다차원 배열을 쉽게 계산하려고 쓰는 파이썬 라이브러리 

넘파이를 쓰는 이유 : 파이썬은 객체지향언어다. 모든 데이터가 객체로 보호되어있다. 그래서 연산이 느리다. 이를 단순 데이터포맷으로 바꿔서 연산하면 속도가 빨라진다. 즉, 연산을 빠르고 쉽게 하려고 사용한다. 

# 주요 기능

1. 넘파이 객체 만들기 
2. 크기(size, shape, ndim, reshape)
3. dtype 메소드 vs 내장함수 type()
4. 특수 행렬

In [5]:
import numpy as np

# 아래 A와 B는 결과적으로 같은 ndarray 객체를 생성합니다. 
A = np.arange(5)
B = np.array([0,1,2,3,4])  # 파이썬 리스트를 numpy ndarray로 변환

# 하지만 C는 좀 다를 것입니다. 
C = np.array([0,1,2,3,'4'])

# D도 A, B와 같은 결과를 내겠지만, B의 방법을 권합니다. 
D = np.ndarray((5,), np.int64, np.array([0,1,2,3,4]))

print(A)
print(type(A))
print(B)
print(type(B))
print(C)
print(type(C))
print(D)
print(type(D))

[0 1 2 3 4]
<class 'numpy.ndarray'>
[0 1 2 3 4]
<class 'numpy.ndarray'>
['0' '1' '2' '3' '4']
<class 'numpy.ndarray'>
[0 1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
A = np.arange(10).reshape(2,5)   # 길이 10의 1차원 행렬을 2X5 2차원 행렬로 바꿔봅니다.

print(A.shape)
print(A.ndim)
print(A.size)

(2, 5)
2
10


In [8]:
A= np.arange(6).reshape(2,3) #원소 6개를 2*3 행렬로 바꾼다
print(A)
print(A.dtype) #입력값의 타입을 알려준다. 숫자라서 int
print(type(A)) #행렬의 자료형이 반환된다.

B = np.array([0,1,2,3,4,5])  
print(B)
print(B.dtype)
print(type(B))

C = np.array([0,1,2,3,'4',5]) #문자열이 한개라도 있으면 숫자를 모두 문자로 바꿔서 값을 일치시킨다
print(C)
print(C.dtype)
print(type(C))

D = np.array([0,1,2,3,[4,5],6])
print(D)
print(D.dtype) #가운데 리스트때문에 같은 타입이 아닌데 오류안남
print(type(D)) # 최상위 클래스인 객체로 지정해서 dtype을 일치한다.

[[0 1 2]
 [3 4 5]]
int64
<class 'numpy.ndarray'>
[0 1 2 3 4 5]
int64
<class 'numpy.ndarray'>
['0' '1' '2' '3' '4' '5']
<U21
<class 'numpy.ndarray'>
[0 1 2 3 list([4, 5]) 6]
object
<class 'numpy.ndarray'>


/home/aiffel-dj54/anaconda3/envs/aiffel/lib/python3.7/site-packages/ipykernel_launcher.py:16: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  app.launch_new_instance()


In [11]:
D = np.array([0,1,2,3,[4,5],6])
print(D[0])
print(type(D[0])) #전체 타입출력은 객체로 했지만 개별로 보면 숫자다
print(D[4])      
print(type(D[4])) #개별 타입은 리스트다.

0
<class 'int'>
[4, 5]
<class 'list'>


/home/aiffel-dj54/anaconda3/envs/aiffel/lib/python3.7/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


### 2-4 특수행렬 & 기본 기능

In [12]:
# 단위행렬
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
# 0행렬
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# 1행렬
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
# 브로드캐스트 
A = np.arange(9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
# ndarray A에 2를 상수배 했을 때,
A * 2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [17]:
# 3 X 3 행렬에 1 X 3 행렬을 더했을 때
A = np.arange(9).reshape(3,3)
B = np.array([1, 2, 3])
print(A)
print(B)
A+B

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[1 2 3]


array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [18]:
# 3 X 3 행렬에 3 X 1 행렬을 더했을 때
A = np.arange(9).reshape(3,3)
C = np.array([[1], [2], [3]])
print(A)
print(C)
A+C

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1]
 [2]
 [3]]


array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [19]:
import numpy as np
print(np.array([1,2])+np.array([3,4]))
print(np.array([1,2])+3)

[4 6]
[4 5]


In [23]:
print([1,2]+[3,4])
print([1,2]+3) #리스트는 이렇게 더할 수 없음 타입을 일치 시켜야한다.

[1, 2, 3, 4]


TypeError: can only concatenate list (not "int") to list

In [24]:
# 행렬도 인덱스가 가능하다 
A = np.arange(9).reshape(3,3)
print(A)
B = A[0]
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]


In [22]:
# 슬라이싱도 가능
A[:-1]

array([[0, 1, 2],
       [3, 4, 5]])

# 3. 데이터의 행렬변환 
넘파이로 데이터를 표현하는 방법 
1. 소리 : 1차원
2. 흑백 : 2차원 0은 검정 255는 흰색
3. 컬러 : 3차원 가로*세로 행렬을 3개 둔다
4. 자연어: 임베딩 과정으로 ndarray 표현 
5. 이미지:

## 구조화된 데이터 Hash 
key value로 구성된 자료구조, key 값을 사용해서 데이터 찾는다.
* 다른 프로그래밍 언어는 maping, dictionary라고 한다.|

In [27]:
treasure_box = {'rope':2,    #coin :pcs 구조를 갖고 있다
                'apple':10,  # 데이터 안에 자체적인 구조를 갖는 데이터가 구조화된 데이터!
                'torch': 6, 
                'gold coin': 50, 
                'knife': 1, 
                'arrow': 30}

coin_per_treasure = {'rope':1,
        'apple':2,
        'torch': 2,
        'gold coin': 5, 
        'knife': 30,
        'arrow': 1}

def total_silver(treasure_box, coin_per_treasure):
    total_coin = 0
    for treasure in treasure_box:
        coin = coin_per_treasure[treasure] * treasure_box[treasure]
        print("{} : {}coins/pcs * {}pcs = {} coins".format(
          treasure, coin_per_treasure[treasure], treasure_box[treasure], coin))
        total_coin += coin
    print('total_coin : ', total_coin)
total_silver(treasure_box, coin_per_treasure)

rope : 1coins/pcs * 2pcs = 2 coins
apple : 2coins/pcs * 10pcs = 20 coins
torch : 2coins/pcs * 6pcs = 12 coins
gold coin : 5coins/pcs * 50pcs = 250 coins
knife : 30coins/pcs * 1pcs = 30 coins
arrow : 1coins/pcs * 30pcs = 30 coins
total_coin :  344


# 4. 판다스로 구조화된 데이터보기

### 왜 판다스를 사용하는가?
넘파이의 ndarray 데이터 구조는 산술작업을 위한 기능을 제공하지만 몇가지 단점이 있다. 이를 보완하고자 pandas가 등장했다!

판다스는 넘파이 모듈을 기반으로 만들어진 패키지로 series, dataframe(표)라는 데이터구조(자료구조)를 제공한다. 

장점은 대용량 데이터 사용가능, 복잡한 처리 손쉽게 가능, 데이터 결합,분리 쉬움

* 데이터를 읽어오는 함수 (pd.read_csv(),pd.read_excel(),pd.read_sql())

## 4-1 Series 
객체를 키와 값으로 표현할 수 있는 자료구조// 리스트, 튜플, numpy로 만들 수 있다.

In [31]:
import pandas as pd
ser = pd.Series(['a','b','c',3])
ser

0    a
1    b
2    c
3    3
dtype: object

In [29]:
ser.values # 값만 뽑기 

array(['a', 'b', 'c', 3], dtype=object)

In [32]:
ser.index # 어디서 어디까지 몇스텝인지 뽑아줌

RangeIndex(start=0, stop=4, step=1)

In [40]:
Country_PhoneNumber = {'Korea': 82, 'America': 1, 'Swiss': 41, 'Italy': 39, 'Japan': 81, 'China': 86, 'Rusia': 7}
ser3 = pd.Series(Country_PhoneNumber)  # 인덱스 값을 설정할 수 있다
ser3

Korea      82
America     1
Swiss      41
Italy      39
Japan      81
China      86
Rusia       7
dtype: int64

In [41]:
ser3['Italy':] # 슬라이싱도 가능하다.

Italy    39
Japan    81
China    86
Rusia     7
dtype: int64

In [43]:
# series 객체, 인덱스는 이름 설정 가능하다. dataframe에서 매우 중요!

ser3.name = 'Country_PhoneNumber' #series 객체의 이름 설정
ser3.index.name = 'Country_Name' # 인덱스의 이름 설정
ser3

Country_Name
Korea      82
America     1
Swiss      41
Italy      39
Japan      81
China      86
Rusia       7
Name: Country_PhoneNumber, dtype: int64

# 4-2 DataFrame
표 같은 자료구조

series : 1 index, 1 column

dic    : key column value column

dataframe: several column

In [46]:
s = pd.DataFrame(data) #dataframe 여러개의 칼럼
s

Region  Sales  Amount  Employee
0    Korea    300      90        20
1  America    200      80        10
2   Chaina    500     100        30
3   Canada    150      30         5
4    Italy     50      10         3

In [47]:
s.columns

Index(['Region', 'Sales', 'Amount', 'Employee'], dtype='object')

In [48]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [50]:
# 인덱스와 칼럼의 값 변경가능 #series에서 이름 설정하는 것과 유사 
s.index=['one','two','three','four','five']
s.columns = ['a','b','c','d']
s  

a    b    c   d
one      Korea  300   90  20
two    America  200   80  10
three   Chaina  500  100  30
four    Canada  150   30   5
five     Italy   50   10   3

# 5. 판다스로 EDA 시작하기 

순서
1. 파일 읽기 
2. data - data.head() - data.tail()- data.columns
3. data.info() : 각 칼럼별로 null값, 자료형 보여줌
4. data.describe() : 기본 통계데이터(개수,평균, 표준편차,최솟값, 사분위수, 최댓값)를 볼 수 있다. 
5. data.insnull().sum() : 결측값 확인- sum(): 데이터 개수의 총합 알 수 있다.  
6. value_counts() : 칼럼별 값의 갯수
7. sum(): 칼럼의 합
8. corr() : 컬럼간의 상관관계를 확인할 수 있다. 
9. drop으로 불필요한 컬럼은 삭제한다 

In [ ]:
# 8. corr() : 컬럼간의 상관관계를 확인할 수 있다. 
# 상관관계를 파악하는건 eda에서 가장 중요한 단계다

print(data['TestsPerformed'].corr(data['TotalPositiveCases']))
print(data['TestsPerformed'].corr(data['Deaths']))
print(data['TotalPositiveCases'].corr(data['Deaths']))

data.corr()

In [140]:
# #9. drop으로 불필요한 컬럼은 삭제한다
data.drop(['Latitude','Longitude','Country','Date','HospitalizedPatients',  'IntensiveCarePatients', 'TotalHospitalizedPatients','HomeConfinement','RegionCode','SNo'], axis=1, inplace=True)

data.corr()

## 판다스 기능 알아보기

In [2]:
import numpy as np
import pandas as pd

In [3]:
s = pd.Series([1,2,3,np.nan,6,8])
s

0    1.0
1    2.0
2    3.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [4]:
dates = pd.date_range("20210213",periods=6)
dates

DatetimeIndex(['2021-02-13', '2021-02-14', '2021-02-15', '2021-02-16',
               '2021-02-17', '2021-02-18'],
              dtype='datetime64[ns]', freq='D')

넘파이의 np.random. randn/rand vs randint

* random.randint : 시작~n-1 사이의 랜덤숫자 1개 뽑기
* random.rand(m,n): 0-1 균일분포 표준정규분포 난수를 matrix array(m,n)생성
* random.randn(m,n): 평균 0, 표준편차 1의 난수를 matrix array(m,n)생성

In [8]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list("ABCD"))
df                

A         B         C         D
2021-02-13  1.858451 -0.320417  0.255877  0.593390
2021-02-14  0.084875  0.228538  0.088387 -1.212965
2021-02-15  0.175790  0.606074  0.827155 -0.423944
2021-02-16  0.135250 -2.277788 -0.021270  0.709799
2021-02-17 -0.291458  0.613773  1.598199 -1.180859
2021-02-18  0.485791  0.360759  0.333600  0.584054

In [10]:
df.index

DatetimeIndex(['2021-02-13', '2021-02-14', '2021-02-15', '2021-02-16',
               '2021-02-17', '2021-02-18'],
              dtype='datetime64[ns]', freq='D')

In [11]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [12]:
df.to_numpy()

array([[ 1.85845068, -0.32041652,  0.25587678,  0.59339002],
       [ 0.08487493,  0.22853814,  0.08838693, -1.21296478],
       [ 0.17579011,  0.60607354,  0.82715544, -0.42394381],
       [ 0.13524994, -2.27778809, -0.02127032,  0.7097995 ],
       [-0.29145831,  0.61377336,  1.59819878, -1.18085936],
       [ 0.48579131,  0.36075877,  0.33360026,  0.58405415]])

In [15]:
df.describe() # 기본 통계데이터(개수,평균, 표준편차,최솟값, 사분위수, 최댓값)를 볼 수 있다.

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.408116 -0.131510  0.513658 -0.155087
std    0.752572  1.105770  0.606694  0.905337
min   -0.291458 -2.277788 -0.021270 -1.212965
25%    0.097469 -0.183178  0.130259 -0.991630
50%    0.155520  0.294648  0.294739  0.080055
75%    0.408291  0.544745  0.703767  0.591056
max    1.858451  0.613773  1.598199  0.709799

In [16]:
df.sort_index(axis=1, ascending=False) #정렬하는 함수 

D         C         B         A
2021-02-13  0.593390  0.255877 -0.320417  1.858451
2021-02-14 -1.212965  0.088387  0.228538  0.084875
2021-02-15 -0.423944  0.827155  0.606074  0.175790
2021-02-16  0.709799 -0.021270 -2.277788  0.135250
2021-02-17 -1.180859  1.598199  0.613773 -0.291458
2021-02-18  0.584054  0.333600  0.360759  0.485791

In [17]:
df["A"] #데이터프레임에 있는 칼럼 a 값만 본다

2021-02-13    1.858451
2021-02-14    0.084875
2021-02-15    0.175790
2021-02-16    0.135250
2021-02-17   -0.291458
2021-02-18    0.485791
Freq: D, Name: A, dtype: float64

In [18]:
df[0:3] #인덱스로 슬라이싱 하는 함수

A         B         C         D
2021-02-13  1.858451 -0.320417  0.255877  0.593390
2021-02-14  0.084875  0.228538  0.088387 -1.212965
2021-02-15  0.175790  0.606074  0.827155 -0.423944

In [20]:
df["20210213":"20210216"] #날짜로 인덱싱 

A         B         C         D
2021-02-13  1.858451 -0.320417  0.255877  0.593390
2021-02-14  0.084875  0.228538  0.088387 -1.212965
2021-02-15  0.175790  0.606074  0.827155 -0.423944
2021-02-16  0.135250 -2.277788 -0.021270  0.709799

In [22]:
df.loc[dates[0]] #첫번째 칼럼에 있는 값을 읽는다 #정수가 아닌 칼럼값을 입력해야한다

A    1.858451
B   -0.320417
C    0.255877
D    0.593390
Name: 2021-02-13 00:00:00, dtype: float64

In [24]:
df.loc[:, ["A", "D"]] #A,D 칼럼에 있는 값을 읽는다.

A         D
2021-02-13  1.858451  0.593390
2021-02-14  0.084875 -1.212965
2021-02-15  0.175790 -0.423944
2021-02-16  0.135250  0.709799
2021-02-17 -0.291458 -1.180859
2021-02-18  0.485791  0.584054

In [26]:
#A칼럼에 0번째 값을 읽는다
df.loc[dates[0], "A"]

1.8584506810529544

In [27]:
df.at[dates[0], "A"]  #하나의 값에만 접근가능

1.8584506810529544

In [29]:
df.iloc[3] #위치 정수를 사용해서 접근 # 정수 입력! 

A    0.135250
B   -2.277788
C   -0.021270
D    0.709799
Name: 2021-02-16 00:00:00, dtype: float64

In [31]:
df.iloc[1, 2] #1번째 행 2번째 열에 있는 값

0.08838693180102046

In [32]:
df.iat[1, 1] #위치정수로 데이터 접근, 하나의 요소만 접근함!

0.2285381429195347

In [36]:
df[df["D"] > 0] #D칼럼 양수인 값만 보여줘! 다른 칼럼에도 영향을 미침 

A         B         C         D
2021-02-13  1.858451 -0.320417  0.255877  0.593390
2021-02-16  0.135250 -2.277788 -0.021270  0.709799
2021-02-18  0.485791  0.360759  0.333600  0.584054

In [38]:
df[df > 0] #음수인 값은 NAN 값 처리한다

A         B         C         D
2021-02-13  1.858451       NaN  0.255877  0.593390
2021-02-14  0.084875  0.228538  0.088387       NaN
2021-02-15  0.175790  0.606074  0.827155       NaN
2021-02-16  0.135250       NaN       NaN  0.709799
2021-02-17       NaN  0.613773  1.598199       NaN
2021-02-18  0.485791  0.360759  0.333600  0.584054

In [39]:
#isin()에 입력된 데이터가 있는지 알려주는 것 
df["E"]=["one","two","three","four","fife","sidc"]
df

A         B         C         D      E
2021-02-13  1.858451 -0.320417  0.255877  0.593390    one
2021-02-14  0.084875  0.228538  0.088387 -1.212965    two
2021-02-15  0.175790  0.606074  0.827155 -0.423944  three
2021-02-16  0.135250 -2.277788 -0.021270  0.709799   four
2021-02-17 -0.291458  0.613773  1.598199 -1.180859   fife
2021-02-18  0.485791  0.360759  0.333600  0.584054   sidc

In [40]:
df[df["E"].isin(["four","two"])] #4와2 순서는 상관없음

A         B         C         D     E
2021-02-14  0.084875  0.228538  0.088387 -1.212965   two
2021-02-16  0.135250 -2.277788 -0.021270  0.709799  four

## 5-1) dataframe 병합
* concat : series,dataframe 이어붙이기 
* merge  : key를 기준으로 합친다.
* join   : 인덱스를 기준으로 합친다. 

## concat() 함수
pd.concat(df_up, df_down, axis=0, join='outer')

In [48]:
df = pd.DataFrame(np.random.randn(3, 3))
df1 = pd.DataFrame(np.random.randn(3, 4))
print(df,"\n")
print(df1)

          0         1         2
0 -0.372866 -1.714588 -1.284424
1 -0.391448  0.091852 -1.397391
2 -1.402223  2.610391 -0.508086 

          0         1         2         3
0 -0.622701 -0.031486 -1.172277 -0.350111
1  1.522234  0.748790 -0.505554  0.880325
2 -0.269710 -1.279379 -1.286113  0.572847


In [53]:
#두 데이터프레임은 행과 열이 다르다 
#기본값으로 axis=0 이라서 위아래로 이어붙일 수 있다

result = pd.concat([df,df1]) 
print(result)

          0         1         2         3
0 -0.372866 -1.714588 -1.284424       NaN
1 -0.391448  0.091852 -1.397391       NaN
2 -1.402223  2.610391 -0.508086       NaN
0 -0.622701 -0.031486 -1.172277 -0.350111
1  1.522234  0.748790 -0.505554  0.880325
2 -0.269710 -1.279379 -1.286113  0.572847


In [54]:
#ignore_index=True를 둬서 인덱스 재배열가능
result = pd.concat([df,df1],ignore_index=True) 
print(result)

          0         1         2         3
0 -0.372866 -1.714588 -1.284424       NaN
1 -0.391448  0.091852 -1.397391       NaN
2 -1.402223  2.610391 -0.508086       NaN
3 -0.622701 -0.031486 -1.172277 -0.350111
4  1.522234  0.748790 -0.505554  0.880325
5 -0.269710 -1.279379 -1.286113  0.572847


In [56]:
#axis=1 은 좌우로 이어붙일 수 있다

result = pd.concat([df,df1],axis=1,ignore_index=True) 
print(result)

          0         1         2         3         4         5         6
0 -0.372866 -1.714588 -1.284424 -0.622701 -0.031486 -1.172277 -0.350111
1 -0.391448  0.091852 -1.397391  1.522234  0.748790 -0.505554  0.880325
2 -1.402223  2.610391 -0.508086 -0.269710 -1.279379 -1.286113  0.572847


In [58]:
#기본값으로 outer(합집합)갖는다. 
#inner(교집합) 설정 가능
result = pd.concat([df,df1],axis=0,ignore_index=True,join='inner') 
print(result)

          0         1         2
0 -0.372866 -1.714588 -1.284424
1 -0.391448  0.091852 -1.397391
2 -1.402223  2.610391 -0.508086
3 -0.622701 -0.031486 -1.172277
4  1.522234  0.748790 -0.505554
5 -0.269710 -1.279379 -1.286113


## merge()
기본값: pd.merge(df_left, df_right, how='inner', on=None)

In [61]:
print(df,"\n")
print(df1)

          0         1         2
0 -0.372866 -1.714588 -1.284424
1 -0.391448  0.091852 -1.397391
2 -1.402223  2.610391 -0.508086 

          0         1         2         3
0 -0.622701 -0.031486 -1.172277 -0.350111
1  1.522234  0.748790 -0.505554  0.880325
2 -0.269710 -1.279379 -1.286113  0.572847


In [62]:
merge_inner = pd.merge(df, df1)
merge_inner #교집합이 없어서 아무것도 안나옴 

Empty DataFrame
Columns: [0, 1, 2, 3]
Index: []

In [68]:
 #outer 기준열(0) 중복여부에 상관없이 모두 출력 #두 중 하나라도 데이터가 없으면nan값
merge_outer = pd.merge(df,df1, how='outer',on=0)
merge_outer 

0       1_x       2_x       1_y       2_y         3
0 -0.372866 -1.714588 -1.284424       NaN       NaN       NaN
1 -0.391448  0.091852 -1.397391       NaN       NaN       NaN
2 -1.402223  2.610391 -0.508086       NaN       NaN       NaN
3 -0.622701       NaN       NaN -0.031486 -1.172277 -0.350111
4  1.522234       NaN       NaN  0.748790 -0.505554  0.880325
5 -0.269710       NaN       NaN -1.279379 -1.286113  0.572847

In [72]:
# merge_left = pd.merge(df,df1, how='left', left_on='1_x', right_on='3')
# merge_left


## join
인덱스를 기준으로 결합한다. merge랑 작동방식은 비슷
* 기본값 Dataframe1.join(Dataframe2. how='left')

In [79]:
left = pd.DataFrame({"key": ["foo", "foo"], "lval": [1, 2]})
right = pd.DataFrame({"key": ["foo", "foo"], "rval": [4, 5]})
print(left)
print(right)

   key  lval
0  foo     1
1  foo     2
   key  rval
0  foo     4
1  foo     5


In [80]:
left.set_index('key', inplace=True)
right.set_index('key', inplace=True)
left.join(right)

lval  rval
key            
foo     1     4
foo     1     5
foo     2     4
foo     2     5

In [85]:
left.join(right, how='inner')

lval  rval
key            
foo     1     4
foo     1     5
foo     2     4
foo     2     5

## 6. group by ** 매우 자주 사용
집단. 그룹별로 데이터를 집계, 요약하는 방법 

과정
* split(그룹별로 나눈다)
* appy(각 그룹별로 함수 적용: sum,count,min,max,mean,std 등)
* combine(그룹별 결과 합치는)


In [88]:
df = pd.DataFrame(
   ....:     {
   ....:         "A": ["foo", "bar", "foo", "bar", "foo", "bar", "foo", "foo"],
   ....:         "B": ["one", "one", "two", "three", "two", "two", "one", "three"],
   ....:         "C": np.random.randn(8),
   ....:         "D": np.random.randn(8),
   ....:     }
   ....: )
df

A      B         C         D
0  foo    one  1.384461  2.941541
1  bar    one -0.676460  1.450835
2  foo    two  0.626057  0.718984
3  bar  three -2.576123 -2.471092
4  foo    two -0.855407 -0.015460
5  bar    two -0.854730  0.599395
6  foo    one  1.883670 -0.639154
7  foo  three -0.410744  1.877474

### apply

In [97]:
#apply
df.groupby("A").sum()

C         D
A                      
bar -4.107313 -0.420862
foo  2.628036  4.883385

In [96]:
df.groupby("A").count() #다 합친갯수 

B  C  D
A           
bar  3  3  3
foo  5  5  5

In [101]:
df.groupby("A").min()

B         C         D
A                           
bar  one -2.576123 -2.471092
foo  one -0.855407 -0.639154

In [102]:
df.groupby("A").max()

B        C         D
A                          
bar  two -0.67646  1.450835
foo  two  1.88367  2.941541

In [98]:
df.groupby(["A", "B"]).sum()

C         D
A   B                        
bar one   -0.676460  1.450835
    three -2.576123 -2.471092
    two   -0.854730  0.599395
foo one    3.268131  2.302387
    three -0.410744  1.877474
    two   -0.229350  0.703524

In [99]:
df.groupby(["A", "B"]).size() #집단별 크기(갯수)

A    B    
bar  one      1
     three    1
     two      1
foo  one      2
     three    1
     two      2
dtype: int64

In [100]:
df.groupby(["A", "B"]).mean() #두 집단간 one끼리의 평균

C         D
A   B                        
bar one   -0.676460  1.450835
    three -2.576123 -2.471092
    two   -0.854730  0.599395
foo one    1.634065  1.151193
    three -0.410744  1.877474
    two   -0.114675  0.351762

In [104]:
df.groupby(["B"]).median() #중앙값

C         D
B                        
one    1.384461  1.450835
three -1.493434 -0.296809
two   -0.854730  0.599395

In [105]:
df.groupby(["A", "B"]).std() # 표준편차 값이 1개인것은 nan

C         D
A   B                        
bar one         NaN       NaN
    three       NaN       NaN
    two         NaN       NaN
foo one    0.352993  2.531934
    three       NaN       NaN
    two    1.047553  0.519331

In [106]:
df.groupby(["A"]).std()

C         D
A                      
bar  1.049102  2.062941
foo  1.159311  1.443414

In [107]:
df.groupby(["A"]).var()

C         D
A                      
bar  1.100615  4.255724
foo  1.344002  2.083444

In [109]:
df.groupby(["A"]).first() #그룹내 첫번째값 #last - 마지막값

B         C         D
A                           
bar  one -0.676460  1.450835
foo  one  1.384461  2.941541

In [110]:
df.groupby(["A", "B"]).describe() #옆으로 길게 나타낸다

C                                                              \
          count      mean       std       min       25%       50%       75%   
A   B                                                                         
bar one     1.0 -0.676460       NaN -0.676460 -0.676460 -0.676460 -0.676460   
    three   1.0 -2.576123       NaN -2.576123 -2.576123 -2.576123 -2.576123   
    two     1.0 -0.854730       NaN -0.854730 -0.854730 -0.854730 -0.854730   
foo one     2.0  1.634065  0.352993  1.384461  1.509263  1.634065  1.758867   
    three   1.0 -0.410744       NaN -0.410744 -0.410744 -0.410744 -0.410744   
    two     2.0 -0.114675  1.047553 -0.855407 -0.485041 -0.114675  0.255691   

                        D                                                    \
                max count      mean       std       min       25%       50%   
A   B                                                                         
bar one   -0.676460   1.0  1.450835       NaN  1.450835  1.450835  1.450835   
    three -2.576123   1.0 -2.471092       NaN -2.471092 -2.471092 -2.471092   
    two   -0.854730   1.0  0.599395       NaN  0.599395  0.599395  0.599395   
foo one    1.883670   2.0  1.151193  2.531934 -0.639154  0.256020  1.151193   
    three -0.410744   1.0  1.877474       NaN  1.877474  1.877474  1.877474   
    two    0.626057   2.0  0.351762  0.519331 -0.015460  0.168151  0.351762   

                               
                75%       max  
A   B                          
bar one    1.450835  1.450835  
    three -2.471092 -2.471092  
    two    0.599395  0.599395  
foo one    2.046367  2.941541  
    three  1.877474  1.877474  
    two    0.535373  0.718984

In [112]:
df.groupby(["A", "B"]).describe().T #세로로 나타낸다 

A             bar                           foo                    
B             one     three       two       one     three       two
C count  1.000000  1.000000  1.000000  2.000000  1.000000  2.000000
  mean  -0.676460 -2.576123 -0.854730  1.634065 -0.410744 -0.114675
  std         NaN       NaN       NaN  0.352993       NaN  1.047553
  min   -0.676460 -2.576123 -0.854730  1.384461 -0.410744 -0.855407
  25%   -0.676460 -2.576123 -0.854730  1.509263 -0.410744 -0.485041
  50%   -0.676460 -2.576123 -0.854730  1.634065 -0.410744 -0.114675
  75%   -0.676460 -2.576123 -0.854730  1.758867 -0.410744  0.255691
  max   -0.676460 -2.576123 -0.854730  1.883670 -0.410744  0.626057
D count  1.000000  1.000000  1.000000  2.000000  1.000000  2.000000
  mean   1.450835 -2.471092  0.599395  1.151193  1.877474  0.351762
  std         NaN       NaN       NaN  2.531934       NaN  0.519331
  min    1.450835 -2.471092  0.599395 -0.639154  1.877474 -0.015460
  25%    1.450835 -2.471092  0.599395  0.256020  1.877474  0.168151
  50%    1.450835 -2.471092  0.599395  1.151193  1.877474  0.351762
  75%    1.450835 -2.471092  0.599395  2.046367  1.877474  0.535373
  max    1.450835 -2.471092  0.599395  2.941541  1.877474  0.718984

#### COMBINE 

향후 더 공부하기 
* https://ponyozzang.tistory.com/291
* https://rfriend.tistory.com/391

# 7. reshape
* np.reshape(변경할 배열, 차원) 또는 배열.reshape(차원)

In [116]:
# 1차원 배열 -> 2차원 
a = [1,2,3,4,5,6,7,8]
b = np.reshape(a,(2,4)) #A를 2행 4열인 2차원으로 바꾼다

print(a,'\n')
print(b)

[1, 2, 3, 4, 5, 6, 7, 8] 

[[1 2 3 4]
 [5 6 7 8]]


In [122]:
c= np.reshape(b,(2,2,2)) #2차원 ->3차원
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [124]:
c=b.reshape(2,2,2) #2행 2열 2개?
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [125]:
c[0] 

array([[1, 2],
       [3, 4]])

reshape 에서 -1의 의미는?


In [126]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [131]:
b.reshape(-1,2) #-1을 하고 뒤에 열의 갯수를 쓰면 그 기준으로 재배열

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [133]:
b.reshape(-1,1) #열의 갯수 1개

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [137]:
#반대로 열의 위치에 -1이면 행기준으로 재배열
b.reshape(1,-1) #행이 1개 : 1차원배열이다. 

array([[1, 2, 3, 4, 5, 6, 7, 8]])